import {
	$modify,
	addr,
	BALL_GRAVITY_MULT,
	BALL_JUMP_VEL,
	BALL_TERMINAL,
	ROBOT_BOOST_MAX,
	ROBOT_GRAVITY_MULT,
	ROBOT_JUMP_VEL,
	ROBOT_TERMINAL,
	UFO_CLICK_BOOST,
	UFO_GRAVITY_FALLING,
	UFO_GRAVITY_RISING,
	UFO_TERMINAL_FALL,
	UFO_TERMINAL_RISE,
	WAVE_SPEED,
} from "./framework";

$modify(
	"PlayerObject::_updateFlyJump_waveBranch",
	"['_updateFlyJump'](_0x130c46){var _0x17dd5f=_0x6e411f;let _0x203040=0.8;",
	[
		"['_updateFlyJump'](_0x130c46){var _0x17dd5f=_0x6e411f;",
		`if(this['p']['_eeDart']){`,
		`this['p'][_0x17dd5f(${addr.yVelocity})]=this[_0x17dd5f(${addr.flipMod})]()*${WAVE_SPEED}*(this['p'][_0x17dd5f(${addr.upKeyDown})]?1:-1);`,
		`return;}`,
		`if(this['p']['_eeUfo']){`,
		`var _uFm=this[_0x17dd5f(${addr.flipMod})]();`,
		`var _uFalling=_uFm>0?this['p'][_0x17dd5f(${addr.yVelocity})]<0:this['p'][_0x17dd5f(${addr.yVelocity})]>0;`,
		`var _uGravMult=_uFalling?${UFO_GRAVITY_FALLING}:${UFO_GRAVITY_RISING};`,
		`this['p'][_0x17dd5f(${addr.yVelocity})]-=1.916398*_0x130c46*_uFm*_uGravMult;`,
		`if(this['p'][_0x17dd5f(${addr.upKeyDown})]&&this['p']['_eeUfoCanClick']){`,
		`this['p']['_eeUfoCanClick']=false;`,
		`var _uTarget=${UFO_CLICK_BOOST}*_uFm;`,
		`var _uCur=this['p'][_0x17dd5f(${addr.yVelocity})];`,
		`if(_uFm>0?_uTarget>_uCur:_uTarget<_uCur){`,
		`this['p'][_0x17dd5f(${addr.yVelocity})]=_uTarget;`,
		`}}`,
		`if(!this['p'][_0x17dd5f(${addr.upKeyDown})]){this['p']['_eeUfoCanClick']=true;}`,
		`if(this['p'][_0x17dd5f(${addr.gravityFlipped})]){`,
		`this['p'][_0x17dd5f(${addr.yVelocity})]=Math.max(this['p'][_0x17dd5f(${addr.yVelocity})],-${UFO_TERMINAL_RISE});`,
		`this['p'][_0x17dd5f(${addr.yVelocity})]=Math.min(this['p'][_0x17dd5f(${addr.yVelocity})],${UFO_TERMINAL_FALL});`,
		`}else{`,
		`this['p'][_0x17dd5f(${addr.yVelocity})]=Math.max(this['p'][_0x17dd5f(${addr.yVelocity})],-${UFO_TERMINAL_FALL});`,
		`this['p'][_0x17dd5f(${addr.yVelocity})]=Math.min(this['p'][_0x17dd5f(${addr.yVelocity})],${UFO_TERMINAL_RISE});`,
		`}`,
		`return;}`,
		"let _0x203040=0.8;",
	].join(""),
);

$modify(
	"PlayerObject::updateJump_ballBranch",
	"if(this['p'][_0x14d343(0x5df)])this[_0x14d343(0x15cf)](_0x3d1c6f);else{",
	[
		"if(this['p']['_eeBall']){",
		`this['p'][_0x14d343(${addr.yVelocity})]-=1.916398*_0x3d1c6f*this[_0x14d343(${addr.flipMod})]()*${BALL_GRAVITY_MULT};`,
		`this['p'][_0x14d343(${addr.gravityFlipped})]`,
		`?this['p'][_0x14d343(${addr.yVelocity})]=Math.min(this['p'][_0x14d343(${addr.yVelocity})],${BALL_TERMINAL})`,
		`:this['p'][_0x14d343(${addr.yVelocity})]=Math.max(this['p'][_0x14d343(${addr.yVelocity})],-${BALL_TERMINAL});`,
		`if(this['p'][_0x14d343(${addr.upKeyDown})]&&this['p'][_0x14d343(${addr.canJump})]&&this['p']['_eeBallCanClick']){`,
		`this['p']['_eeBallCanClick']=false;`,
		`this['p'][_0x14d343(${addr.yVelocity})]=${BALL_JUMP_VEL}*this[_0x14d343(${addr.flipMod})]();`,
		`this['p'][_0x14d343(${addr.gravityFlipped})]=!this['p'][_0x14d343(${addr.gravityFlipped})];`,
		`this['p'][_0x14d343(${addr.isJumping})]=false;`,
		`this['p'][_0x14d343(${addr.canJump})]=false;`,
		`this['p']['onGround']=false;`,
		`this['p'][_0x14d343(${addr.wasBoosted})]=false;`,
		`}`,
		`if(!this['p'][_0x14d343(${addr.upKeyDown})]){this['p']['_eeBallCanClick']=true;}`,
		`}else if(this['p']['_eeRobot']){`,
		`var _rbGrav=1.916398*_0x3d1c6f*this[_0x14d343(${addr.flipMod})]()*${ROBOT_GRAVITY_MULT};`,
		`if(this['p']['_eeRobotBoosting']&&this['p'][_0x14d343(${addr.upKeyDown})]&&this['p']['_eeRobotBoostTime']<${ROBOT_BOOST_MAX}){`,
		`this['p']['_eeRobotBoostTime']+=_0x3d1c6f;`,
		`}else{`,
		`if(this['p']['_eeRobotBoosting']){this['p']['_eeRobotBoosting']=false;}`,
		`this['p'][_0x14d343(${addr.yVelocity})]-=_rbGrav;`,
		`}`,
		`this['p'][_0x14d343(${addr.gravityFlipped})]`,
		`?this['p'][_0x14d343(${addr.yVelocity})]=Math.min(this['p'][_0x14d343(${addr.yVelocity})],${ROBOT_TERMINAL})`,
		`:this['p'][_0x14d343(${addr.yVelocity})]=Math.max(this['p'][_0x14d343(${addr.yVelocity})],-${ROBOT_TERMINAL});`,
		`if(this['p'][_0x14d343(${addr.upKeyDown})]&&this['p'][_0x14d343(${addr.canJump})]&&!this['p']['_eeRobotJumped']){`,
		`this['p']['_eeRobotJumped']=true;`,
		`this['p']['_eeRobotBoosting']=true;`,
		`this['p']['_eeRobotBoostTime']=0;`,
		`this['p'][_0x14d343(${addr.yVelocity})]=${ROBOT_JUMP_VEL}*this[_0x14d343(${addr.flipMod})]();`,
		`this['p'][_0x14d343(${addr.isJumping})]=true;`,
		`this['p'][_0x14d343(${addr.canJump})]=false;`,
		`this['p']['onGround']=false;`,
		`this['p'][_0x14d343(${addr.wasBoosted})]=false;`,
		`}`,
		`if(!this['p'][_0x14d343(${addr.upKeyDown})]){this['p']['_eeRobotJumped']=false;}`,
		`}else if(this['p'][_0x14d343(${addr.isFlying})])this[_0x14d343(${addr._updateFlyJump})](_0x3d1c6f);else{`,
	].join(""),
);
